customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

keybinding:
  universal:
    quit: "q"
    return: "<esc>"
    scrollLeft: "h"
    scrollRight: "l"
    prevTab: "{"
    nextTab: "}"
    confirm: "<enter>"

